-- +goose Up
-- +goose StatementBegin

create table if not exists links (
    id bigint generated by default as identity primary key,
    ref varchar(8) not null,
    target text not null,
    created_at bigint not null,
    created_by text not null,
    expires_at bigint
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
